name: gh-pages
on: [push, pull_request]
jobs:
  cd:
    runs-on: ${{ matrix.os }} # ds

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: cd docs && yarn

      - name: Generate
        run: cd docs && yarn run nuxt generate

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: main
          folder: ./docs/dist
